// Code generated by entc, DO NOT EDIT.

package set

const (
	// Label holds the string label denoting the set type in the database.
	Label = "set"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the set in the database.
	Table = "sets"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "sets"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_set"
)

// Columns holds all SQL columns for set fields.
var Columns = []string{
	FieldID,
	FieldData,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "sets"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_set",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
