// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Set is the predicate function for set builders.
type Set func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
