// Code generated by entc, DO NOT EDIT.

package hook

import (
	"context"
	"dndroller/internal/repo"
	"fmt"
)

// The SetFunc type is an adapter to allow the use of ordinary
// function as Set mutator.
type SetFunc func(context.Context, *repo.SetMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f SetFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	mv, ok := m.(*repo.SetMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.SetMutation", m)
	}
	return f(ctx, mv)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *repo.UserMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	mv, ok := m.(*repo.UserMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.UserMutation", m)
	}
	return f(ctx, mv)
}

// Condition is a hook condition function.
type Condition func(context.Context, repo.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m repo.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m repo.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m repo.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op repo.Op) Condition {
	return func(_ context.Context, m repo.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m repo.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m repo.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m repo.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
//
func If(hk repo.Hook, cond Condition) repo.Hook {
	return func(next repo.Mutator) repo.Mutator {
		return repo.MutateFunc(func(ctx context.Context, m repo.Mutation) (repo.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, repo.Delete|repo.Create)
//
func On(hk repo.Hook, op repo.Op) repo.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, repo.Update|repo.UpdateOne)
//
func Unless(hk repo.Hook, op repo.Op) repo.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) repo.Hook {
	return func(repo.Mutator) repo.Mutator {
		return repo.MutateFunc(func(context.Context, repo.Mutation) (repo.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []repo.Hook {
//		return []repo.Hook{
//			Reject(repo.Delete|repo.Update),
//		}
//	}
//
func Reject(op repo.Op) repo.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []repo.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...repo.Hook) Chain {
	return Chain{append([]repo.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() repo.Hook {
	return func(mutator repo.Mutator) repo.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...repo.Hook) Chain {
	newHooks := make([]repo.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
